// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderService.Database.Entities;

public partial class Order
{
    public Guid OrderId { get; set; }

    public string Product { get; set; }

    public decimal? Price { get; set; }

    public string UserId { get; set; }

    public DateTime? OrderAcceptDateTime { get; set; }
}